<?php

require 'chuckwallaom/om/ChuckwallaBaseNick.php';


/**
 * Skeleton subclass for representing a row from the 'nick' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Jan 27 21:27:35 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    chuckwallaom
 */
class ChuckwallaNick extends ChuckwallaBaseNick {

	public function getChannelNicks($criteria = null, PDO $con = null)
	{
		// make sure propel knows the context
		$this->getContext()->getModel('ChuckwallaNickPeer');
		$this->getContext()->getModel('ChuckwallaChannelNickPeer');

		return parent::getChannelNicks($criteria, $con);
	}

	public function getOrCreateIrcIdentity()
	{
		$identity = $this->getIrcIdentity();
		if(!$identity) {
			$identity = $this->getContext()->getModel('ChuckwallaIrcIdentity');
			$this->setIrcIdentity($identity);
		}
		return $identity;
	}

} // ChuckwallaNick
