<?php

require 'chuckwallaom/om/ChuckwallaBaseMessageLogPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'message_log' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 01/28/07 04:28:35
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    chuckwallaom
 */
class ChuckwallaMessageLogPeer extends ChuckwallaBaseMessageLogPeer {
	public function retrieveSince($channelId, $lastMessageId = null)
	{
		$c = new Criteria();
		$c->add(ChuckwallaMessageLogPeer::CHANNEL_ID, $channelId);
		if($lastMessageId !== null) {
			$c->add(ChuckwallaMessageLogPeer::ID, $lastMessageId, Criteria::GREATER_THAN);
			$c->addAscendingOrderByColumn(ChuckwallaMessageLogPeer::ID);
		} else {
			$c->addDescendingOrderByColumn(ChuckwallaMessageLogPeer::ID);
			$c->setLimit(1);
		}

		return $this->doSelect($c);
	}
} // ChuckwallaMessageLogPeer
