<?php

require 'chuckwallaom/om/ChuckwallaBaseChannel.php';


/**
 * Skeleton subclass for representing a row from the 'channel' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Jan 27 21:27:34 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    chuckwallaom
 */
class ChuckwallaChannel extends ChuckwallaBaseChannel {

} // ChuckwallaChannel
