<?php

require 'chuckwallaom/om/ChuckwallaBaseChannelNickPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'channel_nick' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Jan 27 21:27:35 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    chuckwallaom
 */
class ChuckwallaChannelNickPeer extends ChuckwallaBaseChannelNickPeer {

} // ChuckwallaChannelNickPeer
