<?php

require 'chuckwallaom/om/ChuckwallaBaseCommandsPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'commands' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 01/28/07 01:19:02
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    chuckwallaom
 */
class ChuckwallaCommandsPeer extends ChuckwallaBaseCommandsPeer {

} // ChuckwallaCommandsPeer
