<?php

require 'chuckwallaom/om/ChuckwallaBaseCommands.php';


/**
 * Skeleton subclass for representing a row from the 'commands' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 01/28/07 01:19:02
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    chuckwallaom
 */
class ChuckwallaCommands extends ChuckwallaBaseCommands {

} // ChuckwallaCommands
