<?php

require 'chuckwallaom/om/ChuckwallaBaseMessageLog.php';


/**
 * Skeleton subclass for representing a row from the 'message_log' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 01/28/07 04:28:35
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    chuckwallaom
 */
class ChuckwallaMessageLog extends ChuckwallaBaseMessageLog {

} // ChuckwallaMessageLog
