<?php

require 'chuckwallaom/om/BaseNick.php';


/**
 * Skeleton subclass for representing a row from the 'nick' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Jan 27 19:16:58 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    chuckwallaom
 */
class Nick extends BaseNick {

} // Nick
