<?php
// This file generated by Propel 1.3.0-dev convert-props target on 01/28/07 04:28:35
// from XML runtime conf file D:\home\agavi-td\trunk\dev\om\runtime-conf.xml
return array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'chuckwalla' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'dsn' => 'mysql:host=localhost;dbname=chuckwalla',
          'user' => 'administrator',
          'password' => 'fire2war',
          'options' => 
          array (
            'ATTR_PERSISTENT' => 
            array (
              'value' => false,
            ),
          ),
          'attributes' => 
          array (
            'ATTR_EMULATE_PREPARES' => 
            array (
              'value' => true,
            ),
          ),
          'settings' => 
          array (
            'charset' => 
            array (
              'value' => 'utf8',
            ),
          ),
        ),
        'classes' => 
        array (
          'ChuckwallaChannelMapBuilder' => 'chuckwallaom/map/ChuckwallaChannelMapBuilder.php',
          'ChuckwallaChannelPeer' => 'chuckwallaom/ChuckwallaChannelPeer.php',
          'ChuckwallaChannel' => 'chuckwallaom/ChuckwallaChannel.php',
          'ChuckwallaChannelNickMapBuilder' => 'chuckwallaom/map/ChuckwallaChannelNickMapBuilder.php',
          'ChuckwallaChannelNickPeer' => 'chuckwallaom/ChuckwallaChannelNickPeer.php',
          'ChuckwallaChannelNick' => 'chuckwallaom/ChuckwallaChannelNick.php',
          'ChuckwallaIrcIdentityMapBuilder' => 'chuckwallaom/map/ChuckwallaIrcIdentityMapBuilder.php',
          'ChuckwallaIrcIdentityPeer' => 'chuckwallaom/ChuckwallaIrcIdentityPeer.php',
          'ChuckwallaIrcIdentity' => 'chuckwallaom/ChuckwallaIrcIdentity.php',
          'ChuckwallaNickMapBuilder' => 'chuckwallaom/map/ChuckwallaNickMapBuilder.php',
          'ChuckwallaNickPeer' => 'chuckwallaom/ChuckwallaNickPeer.php',
          'ChuckwallaNick' => 'chuckwallaom/ChuckwallaNick.php',
          'ChuckwallaUserMapBuilder' => 'chuckwallaom/map/ChuckwallaUserMapBuilder.php',
          'ChuckwallaUserPeer' => 'chuckwallaom/ChuckwallaUserPeer.php',
          'ChuckwallaUser' => 'chuckwallaom/ChuckwallaUser.php',
          'ChuckwallaCommandsMapBuilder' => 'chuckwallaom/map/ChuckwallaCommandsMapBuilder.php',
          'ChuckwallaCommandsPeer' => 'chuckwallaom/ChuckwallaCommandsPeer.php',
          'ChuckwallaCommands' => 'chuckwallaom/ChuckwallaCommands.php',
          'ChuckwallaMessageLogMapBuilder' => 'chuckwallaom/map/ChuckwallaMessageLogMapBuilder.php',
          'ChuckwallaMessageLogPeer' => 'chuckwallaom/ChuckwallaMessageLogPeer.php',
          'ChuckwallaMessageLog' => 'chuckwallaom/ChuckwallaMessageLog.php',
        ),
      ),
      'default' => 'chuckwalla',
    ),
    'generator_version' => '1.3.0-dev',
  ),
);