<?php
// This file generated by Propel 1.3.0-dev convert-props target on Sat Jan 27 18:48:43 2007
// from XML runtime conf file /Users/dzuelke/Sites/phpthrowdown/trunk/dev/om/runtime-conf.xml
return array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'chuckwalla' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'dsn' => 'mysql:host=localhost;dbname=chuckwalla',
          'user' => 'chuckwalla',
          'password' => '123qwe',
          'options' => 
          array (
            'ATTR_PERSISTENT' => 
            array (
              'value' => false,
            ),
          ),
          'attributes' => 
          array (
            'ATTR_EMULATE_PREPARES' => 
            array (
              'value' => true,
            ),
          ),
          'settings' => 
          array (
            'charset' => 
            array (
              'value' => 'utf8',
            ),
          ),
        ),
        'classes' => 
        array (
          'BookMapBuilder' => 'chuckwallaom/map/BookMapBuilder.php',
          'BookPeer' => 'chuckwallaom/BookPeer.php',
          'Book' => 'chuckwallaom/Book.php',
        ),
      ),
      'default' => 'chuckwalla',
    ),
    'generator_version' => '1.3.0-dev',
  ),
);