<?php
// This file generated by Propel 1.3.0-dev convert-props target on Sat Jan 27 19:19:34 2007
// from XML runtime conf file /Users/dzuelke/Sites/phpthrowdown/trunk/dev/om/runtime-conf.xml
return array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'chuckwalla' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'dsn' => 'mysql:host=localhost;dbname=chuckwalla',
          'user' => 'chuckwalla',
          'password' => '123qwe',
          'options' => 
          array (
            'ATTR_PERSISTENT' => 
            array (
              'value' => false,
            ),
          ),
          'attributes' => 
          array (
            'ATTR_EMULATE_PREPARES' => 
            array (
              'value' => true,
            ),
          ),
          'settings' => 
          array (
            'charset' => 
            array (
              'value' => 'utf8',
            ),
          ),
        ),
        'classes' => 
        array (
          'ChannelMapBuilder' => 'chuckwallaom/map/ChannelMapBuilder.php',
          'ChannelPeer' => 'chuckwallaom/ChannelPeer.php',
          'Channel' => 'chuckwallaom/Channel.php',
          'ChannelNickMapBuilder' => 'chuckwallaom/map/ChannelNickMapBuilder.php',
          'ChannelNickPeer' => 'chuckwallaom/ChannelNickPeer.php',
          'ChannelNick' => 'chuckwallaom/ChannelNick.php',
          'IrcIdentityMapBuilder' => 'chuckwallaom/map/IrcIdentityMapBuilder.php',
          'IrcIdentityPeer' => 'chuckwallaom/IrcIdentityPeer.php',
          'IrcIdentity' => 'chuckwallaom/IrcIdentity.php',
          'NickMapBuilder' => 'chuckwallaom/map/NickMapBuilder.php',
          'NickPeer' => 'chuckwallaom/NickPeer.php',
          'Nick' => 'chuckwallaom/Nick.php',
          'UserMapBuilder' => 'chuckwallaom/map/UserMapBuilder.php',
          'UserPeer' => 'chuckwallaom/UserPeer.php',
          'User' => 'chuckwallaom/User.php',
        ),
      ),
      'default' => 'chuckwalla',
    ),
    'generator_version' => '1.3.0-dev',
  ),
);