<?php
/************************************************************************
 * Copyright (C) 1990 Jarkko Oikarinen
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 1, or (at your option)
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
class IRCProtocol {
	
	/* Server messages */
	const SERVER_MESSAGE_ERROR = 'ERROR';
	const SERVER_MESSAGE_NOTICE = 'NOTICE';
	const SERVER_MESSAGE_PING = 'PING';
	
	/* Messages */
	const MESSAGE_PRIVMSG = 'PRIVMSG';
	const MESSAGE_NOTICE = 'NOTICE';
	const MESSAGE_JOIN = 'JOIN';
	const MESSAGE_KICK = 'KICK';
	const MESSAGE_KILL = 'KILL';
	const MESSAGE_MODE = 'MODE';
	const MESSAGE_NICK = 'NICK';
	const MESSAGE_PART = 'PART';
	const MESSAGE_PONG = 'PONG';
	const MESSAGE_QUIT = 'QUIT';
	const MESSAGE_INVITE = 'INVITE';
	const MESSAGE_TOPIC = 'TOPIC';
	const MESSAGE_WALLOPS = 'WALLOPS';
	
	/* Numerics */
	const REPLY_WELCOME = 001;
	const REPLY_YOURHOST = 002;
	const REPLY_CREATED = 003;
	const REPLY_MYINFO = 004;
	const REPLY_ISUPPORT = 005;
	
	const REPLY_REDIR = 10;
	
	const REPLY_REMOTEISUPPORT = 105;
	
	const ERROR_NOSUCHNICK = 401;
	const ERROR_NOSUCHSERVER = 402;
	const ERROR_NOSUCHCHANNEL = 403;
	const ERROR_CANNOTSENDTOCHAN = 404;
	const ERROR_TOOMANYCHANNELS = 405;
	const ERROR_WASNOSUCHNICK = 406;
	const ERROR_TOOMANYTARGETS = 407;
	const ERROR_NOSUCHSERVICE = 408;
	const ERROR_NOORIGIN = 409;
	
	const ERROR_NORECIPIENT = 411;
	const ERROR_NOTEXTTOSEND = 412;
	const ERROR_NOTOPLEVEL = 413;
	const ERROR_WILDTOPLEVEL = 414;
	
	const ERROR_UNKNOWNCOMMAND = 421;
	const ERROR_NOMOTD = 422;
	const ERROR_NOADMININFO = 423;
	const ERROR_FILEERROR = 424;
	const ERROR_NOOPERMOTD = 425;
	
	const ERROR_TOOMANYAWAY = 429;
	
	const ERROR_NONICKNAMEGIVEN = 431;
	const ERROR_ERRONEUSNICKNAME = 432;
	const ERROR_NICKNAMEINUSE = 433;
	const ERROR_NORULES = 434;
	const ERROR_SERVICECONFUSED = 435;
	const ERROR_NICKCOLLISION = 436;
	const ERROR_BANNICKCHANGE = 437;
	const ERROR_NCHANGETOOFAST = 438;
	const ERROR_TARGETTOOFAST = 439;
	const ERROR_SERVICESDOWN = 440;
	
	const ERROR_USERNOTINCHANNEL = 441;
	const ERROR_NOTONCHANNEL = 442;
	const ERROR_USERONCHANNEL = 443;
	const ERROR_NOLOGIN = 444;
	const ERROR_SUMMONDISABLED = 445;
	const ERROR_USERSDISABLED = 446;
	const ERROR_NONICKCHANGE = 447;
	
	const ERROR_NOTREGISTERED = 451;
	
	const ERROR_HOSTILENAME = 455;
	
	const ERROR_NOHIDING = 459;
	const ERROR_NOTFORHALFOPS = 460;
	const ERROR_NEEDMOREPARAMS = 461;
	const ERROR_ALREADYREGISTRED = 462;
	const ERROR_NOPERMFORHOST = 463;
	const ERROR_PASSWDMISMATCH = 464;
	const ERROR_YOUREBANNEDCREEP = 465;
	const ERROR_YOUWILLBEBANNED = 466;
	const ERROR_KEYSET = 467;
	const ERROR_ONLYSERVERSCANCHANGE = 468;
	const ERROR_LINKSET = 469;
	const ERROR_LINKCHANNEL = 470;
	const ERROR_CHANNELISFULL = 471;
	const ERROR_UNKNOWNMODE = 472;
	const ERROR_INVITEONLYCHAN = 473;
	const ERROR_BANNEDFROMCHAN = 474;
	const ERROR_BADCHANNELKEY = 475;
	const ERROR_BADCHANMASK = 476;
	const ERROR_NEEDREGGEDNICK = 477;
	const ERROR_BANLISTFULL = 478;
	const ERROR_LINKFAIL = 479;
	const ERROR_CANNOTKNOCK = 480;
	
	const ERROR_NOPRIVILEGES = 481;
	const ERROR_CHANOPRIVSNEEDED = 482;
	const ERROR_CANTKILLSERVER = 483;
	const ERROR_ATTACKDENY = 484;
	const ERROR_KILLDENY = 485;
	
	const ERROR_NONONREG = 486;
	const ERROR_NOTFORUSERS = 487;
	const ERROR_HTMDISABLED = 488;
	const ERROR_SECUREONLYCHAN = 489;
	const ERROR_NOSWEAR = 490;
	const ERROR_NOOPERHOST = 491;
	const ERROR_NOCTCP = 492;
	
	const ERROR_CHANOWNPRIVNEEDED = 499;
	
	const ERROR_TOOMANYJOINS = 500;
	const ERROR_UMODEUNKNOWNFLAG = 501;
	const ERROR_USERSDONTMATCH = 502;
	
	const ERROR_SILELISTFULL = 511;
	const ERROR_TOOMANYWATCH = 512;
	const ERROR_NEEDPONG = 513;
	
	const ERROR_TOOMANYDCC = 514;
	
	const ERROR_DISABLED = 517;
	const ERROR_NOINVITE = 518;
	const ERROR_ADMONLY = 519;
	const ERROR_OPERONLY = 520;
	const ERROR_LISTSYNTAX = 521;
	
	const REPLY_NONE = 300;
	const REPLY_AWAY = 301;
	const REPLY_USERHOST = 302;
	const REPLY_ISON = 303;
	const REPLY_TEXT = 304;
	const REPLY_UNAWAY = 305;
	const REPLY_NOWAWAY = 306;
	const REPLY_WHOISREGNICK = 307;
	const REPLY_RULESSTART = 308;
	const REPLY_ENDOFRULES = 309;
	const REPLY_WHOISHELPOP = 310;
	
	const REPLY_WHOISUSER = 311;
	const REPLY_WHOISSERVER = 312;
	const REPLY_WHOISOPERATOR = 313;
	
	const REPLY_WHOWASUSER = 314;
	const REPLY_ENDOFWHOWAS = 369;
	
	const REPLY_WHOISCHANOP = 316;
	const REPLY_WHOISIDLE = 317;
	
	const REPLY_ENDOFWHOIS = 318;
	const REPLY_WHOISCHANNELS = 319;
	const REPLY_WHOISSPECIAL = 320;
	const REPLY_LISTSTART = 321;
	const REPLY_LIST = 322;
	const REPLY_LISTEND = 323;
	const REPLY_CHANNELMODEIS = 324;
	const REPLY_CREATIONTIME = 329;
	const REPLY_NOTOPIC = 331;
	const REPLY_TOPIC = 332;
	const REPLY_TOPICWHOTIME = 333;
	
	const REPLY_INVITELIST = 336;
	const REPLY_ENDOFINVITELIST = 337;
	
	const REPLY_LISTSYNTAX = 334;
	const REPLY_WHOISBOT = 335;
	const REPLY_USERIP = 340;
	const REPLY_INVITING = 341;
	const REPLY_SUMMONING = 342;
	
	const REPLY_VERSION = 351;
	
	const REPLY_WHOREPLY = 352;
	const REPLY_ENDOFWHO = 315;
	const REPLY_NAMREPLY = 353;
	const REPLY_ENDOFNAMES = 366;
	const REPLY_INVEXLIST = 346;
	const REPLY_ENDOFINVEXLIST = 347;
	
	const REPLY_EXLIST = 348;
	const REPLY_ENDOFEXLIST = 349;
	const REPLY_KILLDONE = 361;
	const REPLY_CLOSING = 362;
	const REPLY_CLOSEEND = 363;
	const REPLY_LINKS = 364;
	const REPLY_ENDOFLINKS = 365;
	
	const REPLY_BANLIST = 367;
	const REPLY_ENDOFBANLIST = 368;
	
	const REPLY_INFO = 371;
	const REPLY_MOTD = 372;
	const REPLY_INFOSTART = 373;
	const REPLY_ENDOFINFO = 374;
	const REPLY_MOTDSTART = 375;
	const REPLY_ENDOFMOTD = 376;
	
	const REPLY_WHOISHOST = 378;
	const REPLY_WHOISMODES = 379;
	const REPLY_YOUREOPER = 381;
	const REPLY_REHASHING = 382;
	const REPLY_YOURESERVICE = 383;
	const REPLY_MYPORTIS = 384;
	const REPLY_NOTOPERANYMORE = 385;
	const REPLY_QLIST = 386;
	const REPLY_ENDOFQLIST = 387;
	const REPLY_ALIST = 388;
	const REPLY_ENDOFALIST = 389;
	
	const REPLY_TIME = 391;
	const REPLY_USERSSTART = 392;
	const REPLY_USERS = 393;
	const REPLY_ENDOFUSERS = 394;
	const REPLY_NOUSERS = 395;
	
	const REPLY_TRACELINK = 200;
	const REPLY_TRACECONNECTING = 201;
	const REPLY_TRACEHANDSHAKE = 202;
	const REPLY_TRACEUNKNOWN = 203;
	
	const REPLY_TRACEOPERATOR = 204;
	const REPLY_TRACEUSER = 205;
	const REPLY_TRACESERVER = 206;
	const REPLY_TRACESERVICE = 207;
	const REPLY_TRACENEWTYPE = 208;
	const REPLY_TRACECLASS = 209;
	
	const REPLY_STATSHELP = 210;
	const REPLY_STATSLINKINFO = 211;
	const REPLY_STATSCOMMANDS = 212;
	const REPLY_STATSCLINE = 213;
	const REPLY_STATSOLDNLINE = 214;
	
	const REPLY_STATSILINE = 215;
	const REPLY_STATSKLINE = 216;
	const REPLY_STATSQLINE = 217;
	const REPLY_STATSYLINE = 218;
	const REPLY_ENDOFSTATS = 219;
	const REPLY_STATSBLINE = 220;
	
	const REPLY_UMODEIS = 221;
	const REPLY_SQLINE_NICK = 222;
	const REPLY_STATSGLINE = 223;
	const REPLY_STATSTLINE = 224;
	const REPLY_STATSELINE = 225;
	const REPLY_STATSNLINE = 226;
	const REPLY_STATSVLINE = 227;
	const REPLY_STATSBANVER = 228;
	const REPLY_STATSSPAMF = 229;
	const REPLY_STATSEXCEPTTKL = 230;
	const REPLY_SERVICEINFO = 231;
	const REPLY_RULES = 232;
	const REPLY_SERVICE = 233;
	const REPLY_SERVLIST = 234;
	const REPLY_SERVLISTEND = 235;
	
	const REPLY_STATSLLINE = 241;
	const REPLY_STATSUPTIME = 242;
	const REPLY_STATSOLINE = 243;
	const REPLY_STATSHLINE = 244;
	const REPLY_STATSSLINE = 245;
	const REPLY_STATSXLINE = 247;
	const REPLY_STATSULINE = 248;
	const REPLY_STATSDEBUG = 249;
	const REPLY_STATSCONN = 250;
	
	const REPLY_LUSERCLIENT = 251;
	const REPLY_LUSEROP = 252;
	const REPLY_LUSERUNKNOWN = 253;
	const REPLY_LUSERCHANNELS = 254;
	const REPLY_LUSERME = 255;
	const REPLY_ADMINME = 256;
	const REPLY_ADMINLOC1 = 257;
	const REPLY_ADMINLOC2 = 258;
	const REPLY_ADMINEMAIL = 259;
	
	const REPLY_TRACELOG = 261;
	const REPLY_LOCALUSERS = 265;
	const REPLY_GLOBALUSERS = 266;
	
	const REPLY_SILELIST = 271;
	const REPLY_ENDOFSILELIST = 272;
	const REPLY_STATSDLINE = 275;
	
	const REPLY_HELPHDR = 290;
	const REPLY_HELPOP = 291;
	const REPLY_HELPTLR = 292;
	const REPLY_HELPHLP = 293;
	const REPLY_HELPFWD = 294;
	const REPLY_HELPIGN = 295;
	
	const REPLY_MAP = 006;
	const REPLY_MAPMORE = 610;
	const REPLY_MAPEND = 007;
	
	const ERROR_WHOSYNTAX = 522;
	const ERROR_WHOLIMEXCEED = 523;
	const ERROR_OPERSPVERIFY = 524;
	
	const REPLY_SNOMASK = 8;
}
?>