<?php


/**
 * This class adds structure of 'channel_nick' table to 'chuckwalla' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Jan 27 21:37:46 2007
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    chuckwallaom.map
 */
class ChuckwallaChannelNickMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'chuckwallaom.map.ChuckwallaChannelNickMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ChuckwallaChannelNickPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ChuckwallaChannelNickPeer::TABLE_NAME);
		$tMap->setPhpName('ChannelNick');
		$tMap->setClassname('ChuckwallaChannelNick');

		$tMap->setUseIdGenerator(false);

		$tMap->addForeignPrimaryKey('CHANNEL_ID', 'ChannelId', 'INTEGER' , 'channel', 'ID', true, null);

		$tMap->addForeignPrimaryKey('NICK_ID', 'NickId', 'INTEGER' , 'nick', 'ID', true, null);

	} // doBuild()

} // ChuckwallaChannelNickMapBuilder
